name: Deploy Resume Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04   # <<<<< use 22.04 instead of latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      run: |
        aws s3 sync . s3://www.mkwdd.com --delete --exclude ".git/*" --exclude ".github/*"

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id E3UJZPQKOSNWYT --paths "/*" 
