name: Deploy Resume Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      uses: aws-actions/aws-cli-action@v1
      with:
        aws-cli-command: s3 sync . s3://www.mkwdd.com --delete --exclude ".git/*" --exclude ".github/*"

    - name: Invalidate CloudFront Cache
      uses: aws-actions/aws-cli-action@v1
      with:
        aws-cli-command: cloudfront create-invalidation --distribution-id E3UJZPQKOSNWYT --paths "/*"
